apiVersion: apps/v1
kind: Deployment
metadata:
  name: myshoppingclient-deployment
  labels:
    app: myshoppingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myshoppingclient
  template:
    metadata:
      labels:
        app: myshoppingclient
    spec:
      containers:
        - name: myshoppingclient
          image: myshoppingacr.azurecr.io/myshoppingclient:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: myshoppingapi-configmap
                    key: shoppingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: myshoppingclient-service
spec:
  type: LoadBalancer
  selector:
    app: myshoppingclient
  ports:
    - protocol: TCP
      port: 80